.PHONY: clean All

All:
	@echo "----------Building project:[ RTProfileSelector - Release ]----------"
	@"$(MAKE)" -f  "RTProfileSelector.mk"
clean:
	@echo "----------Cleaning project:[ RTProfileSelector - Release ]----------"
	@"$(MAKE)" -f  "RTProfileSelector.mk" clean
